openapi: '3.0.2'
info:
  title: 'Simple demo'
  version: 0.3.0
servers:
  - url: 'https://apis.washswat.com'
paths:
  /simple:
    get:
      summary: 'REST & Message Queue'
      description: 'sample app'
      tags: 
      - demo
      operationId: demoRequest
      responses:
        '200':
          description: '성공'
          content:
            'application/json':
              schema:
                type: object
                $ref: '#/components/schemas/demoResponse'
components:
  schemas:
    demoResponse:
      description: 'demo 호출의 응답'
      properties:
        result:
          type: string
          description: 'Result string'